add version update check on rtx version #74
jdxcode/rtx pull request #142
Opened 2023-02-17 14:19 UTC by roele

Thought i give this a try as my very first attempt at working with Rust, so bare with me if the code is far away from best practices.

I wonder if the warning should be written as a log message with log level warn or to the standard out. I am also struggling to add tests for this since i could not figure out how to test log output for simplelog or mock the minreq request. Both topics i need to read up on.

2023-02-17 14:41 UTC, jdxcode requested changes
this is a great start, apologies that my feedback is so nitpicky here but I definitely want to make sure we do this correctly since I don't want to mess up `rtx version` in any situation

2023-02-17 14:41 UTC, jdxcode commented on src/cli/version.rs
> +            show_latest();
this should go after `show_version()`. I know that might seem a bit weird from a UX perspective, but it makes it so the user sees the version immediately regardless of anything that might happen with the remote fetching

2023-02-17 14:41 UTC, jdxcode commented on src/cli/version.rs
> +    let current = Versioning::new(current.as_str()).unwrap();
```suggestion
    let current = Versioning::new(env!("CARGO_PKG_VERSION")).unwrap();
```

what you're doing here is taking `env!("CARGO_PKG_VERSION")`, converting it from a `&str` into a String, then calling `as_str()` which converts it back again. There's no need to do that conversion.

2023-02-17 14:41 UTC, jdxcode commented on src/cli/version.rs
> +    let response = minreq::get("https://rtx.jdxcode.com/VERSION")
let's go with reqwest since it's the more popular client. By default it would use async which would require us adding tokio which would require a fair bit of changes, but you can use the blocking version of reqwest that won't require tokio.

Follow these instructions and it should be about the same as this: https://github.com/seanmonstar/reqwest#blocking-client

Another thing this must have is a short timeout. We don't want to block on this for any significant amount of time. I think to do that you'll need to construct a RequestBuilder with reqwest: https://dtantsur.github.io/rust-openstack/reqwest/struct.ClientBuilder.html

Make the timeout 1 second.

2023-02-17 14:41 UTC, jdxcode commented on src/cli/version.rs
> +    match response.status_code {
with reqwest, you can use `error_for_status` to do this instead: https://docs.rs/reqwest/latest/reqwest/struct.Response.html#method.error_for_status

if there is an error, record it with `debug!()` and return `None`. The output of this function should be either `None` if there was an error with http parsing. (This means the return type should not be `Result<>` but `Option<Version>`)

I would put the version parsing in here as well, but instead of calling `.unwrap()`, call [`.ok()`](https://doc.rust-lang.org/std/result/enum.Result.html#method.ok). What that does is make it so if version parsing fails it won't return an error, it'll return None.

The point of all of this is that this function wouldn't be able to return any error, only None or Some(Version). If it's none, we can compare the value, otherwise we don't check the version.

2023-02-17 14:41 UTC, jdxcode commented on src/cli/version.rs
> +const LATEST_VERSION_UNKNOWN: &str = "0.0.0";
let's get rid of this, as explained below if the version isn't what we expect or anything goes wrong we simply just shouldn't attempt to show the warning

2023-02-17 14:41 UTC, jdxcode commented on src/cli/doctor.rs
> +            warn!("rtx version {} available", latest)
this is a good addition, but let's change the messaging a bit
```suggestion
            warn!("new rtx version {} available, currently on {}", latest, env!("CARGO_PKG_VERSION"))
```

2023-02-17 14:41 UTC, jdxcode commented
let me know if you struggle with any parts here, join the discord if you want to chat about it

2023-02-17 14:42 UTC, jdxcode commented
don't worry about any new automated tests for this. I'm not concerned about validating this and it would be hard to do.

2023-02-17 14:44 UTC, jdxcode commented on src/cli/version.rs
> +    let response = minreq::get("https://rtx.jdxcode.com/VERSION")
this should also resolve the openssl build failures we're getting in CI

2023-02-17 17:35 UTC, jankatins commented
This is BTW a nice crate for self updates from e.g. github releases, if you want that as well: https://github.com/jaemk/self_update

2023-02-17 22:05 UTC, roele commented
@jdxcode Thanks a lot for the detailed comments, this helps a lot and is much appreciated.

2023-02-18 14:56 UTC, jdxcode commented
run `just lint-fix` to fix the linter issues

2023-02-18 14:57 UTC, jdxcode commented on Cargo.toml
> +reqwest = { version = "0.11.14", features = ["blocking"] }
```suggestion
reqwest = { version = "0.11.14", features = ["blocking"] }
openssl = { version = "0.10", features = ["vendored"] }
```

I think this will fix the build

2023-02-18 15:03 UTC, jdxcode commented on src/cli/version.rs
> +            show_latest();
do you think we could move this to line 42 instead? I think if we did that the tests would run it (of course this wouldn't validate it's actually working, but we can at least verify nothing is panicking)

2023-02-18 20:43 UTC, roele commented on Cargo.toml
> +reqwest = { version = "0.11.14", features = ["blocking"] }
agree on keeping it since https is pretty much standard these days

2023-02-18 20:58 UTC, jdxcode commented
I believe that E2E test is failing in main for some reason since I had it on #145

2023-02-18 21:19 UTC, roele commented
e2e seems to fail because of direnv which also fails on my local machine (unit, e2e) but i don't have it intalled. also `test-coverage` won't run on my machine because tarpaulin cannot be found and adding it via cargo causes dependency issues with indexmap.

2023-02-19 01:19 UTC, jdxcode commented
yeah don't worry about that E2E failure, I'm fixing it in a different PR. This one looks ready, do you want to mark it not as draft?

2023-02-19 01:27 UTC, jdxcode approved these changes

2023-02-19 03:52 UTC, merged

2023-02-19 03:52 UTC, jdxcode commented
thanks for this!