WIP Test isntallation of all plugins
jdxcode/rtx pull request #182
Opened 2023-02-22 18:04 UTC by gerbal

This PR adds a Github Actions workflow to test all currently published asdf plugins.  Running as a seperate workflow should prevent this blocking the main CI workflow. 

I took a test run of rtx to replace asdf and noticed several plugins (erlang, just) did not install correctly on my local machine. This PR attempts to ensure devs can know whether the latest version of each plugin has experienced regressions or incompatibilities with rtx.

2023-02-22 19:28 UTC, jdxcode commented
I started [something similar](https://github.com/jdxcode/rtx/blob/main/e2e/test_top_runtimes) that isn't currently active but has an advantage over this in that it actually validates the runtimes work. We could increase the number there a bit but I don't think we need to target every single asdf plugin (I bet a lot of them don't even work in asdf)

2023-02-22 19:28 UTC, jdxcode commented
here is the full list btw:

```
687	nodejs	 https://github.com/asdf-vm/asdf-nodejs.git
506	ruby	 https://github.com/asdf-vm/asdf-ruby.git
470	python	 https://github.com/danhper/asdf-python.git
395	direnv	 https://github.com/asdf-community/asdf-direnv.git
353	elixir	 https://github.com/asdf-vm/asdf-elixir.git
351	erlang	 https://github.com/asdf-vm/asdf-erlang.git
322	golang	 https://github.com/kennyp/asdf-golang.git
285	java	 https://github.com/halcyon/asdf-java.git
169	waypoint	 https://github.com/asdf-community/asdf-hashicorp.git
169	vault	 https://github.com/asdf-community/asdf-hashicorp.git
169	tfc-agent	 https://github.com/asdf-community/asdf-hashicorp.git
169	terraform-ls	 https://github.com/asdf-community/asdf-hashicorp.git
169	terraform	 https://github.com/asdf-community/asdf-hashicorp.git
169	serf	 https://github.com/asdf-community/asdf-hashicorp.git
169	sentinel	 https://github.com/asdf-community/asdf-hashicorp.git
169	packer	 https://github.com/asdf-community/asdf-hashicorp.git
169	nomad	 https://github.com/asdf-community/asdf-hashicorp.git
169	levant	 https://github.com/asdf-community/asdf-hashicorp.git
169	consul	 https://github.com/asdf-community/asdf-hashicorp.git
169	boundary	 https://github.com/asdf-community/asdf-hashicorp.git
160	php	 https://github.com/asdf-community/asdf-php.git
147	postgres	 https://github.com/smashedtoatoms/asdf-postgres.git
117	rust	 https://github.com/code-lever/asdf-rust.git
113	yarn	 https://github.com/twuni/asdf-yarn.git
102	deno	 https://github.com/asdf-community/asdf-deno.git
93	kubectl	 https://github.com/asdf-community/asdf-kubectl.git
82	action-validator	 https://github.com/mpalmer/action-validator.git
75	dotnet-core	 https://github.com/emersonsoares/asdf-dotnet-core.git
73	flutter	 https://github.com/oae/asdf-flutter.git
68	crystal	 https://github.com/asdf-community/asdf-crystal.git
49	neovim	 https://github.com/richin13/asdf-neovim.git
47	poetry	 https://github.com/asdf-community/asdf-poetry.git
46	haskell	 https://github.com/asdf-community/asdf-haskell.git
42	link	 https://github.com/asdf-community/asdf-link.git
38	lua	 https://github.com/Stratus3D/asdf-lua.git
38	bun	 https://github.com/cometkim/asdf-bun.git
35	redis	 https://github.com/smashedtoatoms/asdf-redis.git
35	gcloud	 https://github.com/jthegedus/asdf-gcloud.git
34	helm	 https://github.com/Antiarchitect/asdf-helm.git
33	gleam	 https://github.com/vic/asdf-gleam.git
32	awscli	 https://github.com/MetricMike/asdf-awscli.git
30	dart	 https://github.com/PatOConnor43/asdf-dart.git
28	conan	 https://github.com/amrox/asdf-pyapp.git
28	awsebcli	 https://github.com/amrox/asdf-pyapp.git
28	aws-sam-cli	 https://github.com/amrox/asdf-pyapp.git
28	ansible-base	 https://github.com/amrox/asdf-pyapp.git
27	kotlin	 https://github.com/asdf-community/asdf-kotlin.git
26	pnpm	 https://github.com/jonathanmorley/asdf-pnpm.git
23	ocaml	 https://github.com/asdf-community/asdf-ocaml.git
22	rebar	 https://github.com/Stratus3D/asdf-rebar.git
20	julia	 https://github.com/rkyleg/asdf-julia.git
20	elm	 https://github.com/asdf-community/asdf-elm.git
18	R	 https://github.com/asdf-community/asdf-r.git
17	nim	 https://github.com/asdf-community/asdf-nim.git
17	alias	 https://github.com/andrewthauer/asdf-alias.git
16	mysql	 https://github.com/iroddis/asdf-mysql.git
16	minikube	 https://github.com/alvarobp/asdf-minikube.git
16	gradle	 https://github.com/rfrancis/asdf-gradle.git
15	zig	 https://github.com/cheetah/asdf-zig.git
15	shellcheck	 https://github.com/luizm/asdf-shellcheck.git
15	scala	 https://github.com/asdf-community/asdf-scala.git
15	maven	 https://github.com/halcyon/asdf-maven.git
15	kustomize	 https://github.com/Banno/asdf-kustomize.git
15	graalvm	 https://github.com/asdf-community/asdf-graalvm.git
14	sbcl	 https://github.com/smashedtoatoms/asdf-sbcl.git
14	protoc	 https://github.com/paxosglobal/asdf-protoc.git
14	perl	 https://github.com/ouest/asdf-perl.git
12	tmux	 https://github.com/aphecetche/asdf-tmux.git
12	opam	 https://github.com/asdf-community/asdf-opam.git
12	haxe	 https://github.com/asdf-community/asdf-haxe.git
12	go-sdk	 https://github.com/yacchi/asdf-go-sdk.git
12	firebase	 https://github.com/jthegedus/asdf-firebase.git
11	racket	 https://github.com/asdf-community/asdf-racket.git
11	clojure	 https://github.com/asdf-community/asdf-clojure.git
10	github-cli	 https://github.com/bartlomiejdanek/asdf-github-cli.git
10	clusterctl	 https://github.com/pfnet-research/asdf-clusterctl.git
9	starship	 https://github.com/grimoh/asdf-starship.git
9	shfmt	 https://github.com/luizm/asdf-shfmt.git
9	mongodb	 https://github.com/sylph01/asdf-mongodb.git
9	kube-credential-cache	 https://github.com/ryodocx/kube-credential-cache.git
9	caddy	 https://github.com/salasrod/asdf-caddy.git
8	swift	 https://github.com/fcrespo82/asdf-swift.git
8	sqlite	 https://github.com/cLupus/asdf-sqlite.git
8	imagemagick	 https://github.com/mangalakader/asdf-imagemagick.git
8	aws-vault	 https://github.com/karancode/asdf-aws-vault.git
7	yq	 https://github.com/sudermanjr/asdf-yq.git
7	vim	 https://github.com/tsuyoshicho/asdf-vim.git
7	syncher	 https://github.com/nwillc/syncher.git
7	lfe	 https://github.com/asdf-community/asdf-lfe.git
7	leiningen	 https://github.com/miorimmax/asdf-lein.git
7	docker-slim	 https://github.com/everpeace/asdf-docker-slim.git
7	buf	 https://github.com/truepay/asdf-buf.git
7	bazel	 https://github.com/rajatvig/asdf-bazel.git
6	zellij	 https://github.com/chessmango/asdf-zellij.git
6	swiprolog	 https://github.com/mracos/asdf-swiprolog.git
6	stack	 https://github.com/sestrella/asdf-ghcup.git
6	sops	 https://github.com/feniix/asdf-sops.git
6	pulumi	 https://github.com/canha/asdf-pulumi.git
6	ninja	 https://github.com/asdf-community/asdf-ninja.git
6	minio	 https://github.com/aeons/asdf-minio.git
6	k9s	 https://github.com/looztra/asdf-k9s.git
6	jq	 https://github.com/azmcode/asdf-jq.git
6	golangci-lint	 https://github.com/hypnoglow/asdf-golangci-lint.git
6	gauche	 https://github.com/sakuro/asdf-gauche.git
6	flux2	 https://github.com/tablexi/asdf-flux2.git
6	elasticsearch	 https://github.com/asdf-community/asdf-elasticsearch.git
6	dotty	 https://github.com/vic/asdf-dotty.git
6	dotnet	 https://github.com/hensou/asdf-dotnet
6	bundler	 https://github.com/jonathanmorley/asdf-bundler.git
6	bats	 https://github.com/timgluz/asdf-bats.git
6	aria2	 https://github.com/asdf-community/asdf-aria2.git
6	1password-cli	 https://github.com/NeoHsu/asdf-1password-cli.git
5	terragrunt	 https://github.com/ohmer/asdf-terragrunt.git
5	rabbitmq	 https://github.com/w-sanches/asdf-rabbitmq.git
5	purescript	 https://github.com/nsaunders/asdf-purescript.git
5	please	 https://github.com/asdf-community/asdf-please.git
5	opa	 https://github.com/tochukwuvictor/asdf-opa.git
5	lean	 https://github.com/asdf-community/asdf-lean.git
5	lazygit	 https://github.com/nklmilojevic/asdf-lazygit.git
5	kubebuilder	 https://github.com/virtualstaticvoid/asdf-kubebuilder.git
5	gohugo	 https://github.com/nklmilojevic/asdf-hugo.git
5	fzf	 https://github.com/kompiro/asdf-fzf.git
5	coq	 https://github.com/gingerhot/asdf-coq.git
5	chezmoi	 https://github.com/joke/asdf-chezmoi.git
5	cf	 https://github.com/mattysweeps/asdf-cf.git
5	ccache	 https://github.com/asdf-community/asdf-ccache.git
4	zoxide	 https://github.com/nyrst/asdf-zoxide
4	zola	 https://github.com/salasrod/asdf-zola.git
4	wasi-sdk	 https://github.com/coolreader18/asdf-wasi-sdk.git
4	stern	 https://github.com/looztra/asdf-stern.git
4	steampipe	 https://github.com/carnei-ro/asdf-steampipe.git
4	solidity	 https://github.com/diegodorado/asdf-solidity.git
4	saml2aws	 https://github.com/elementalvoid/asdf-saml2aws.git
4	raku	 https://github.com/m-dango/asdf-raku.git
4	peco	 https://github.com/asdf-community/asdf-peco.git
4	operator-sdk	 https://github.com/Medium/asdf-operator-sdk.git
4	openresty	 https://github.com/smashedtoatoms/asdf-openresty.git
4	neko	 https://github.com/asdf-community/asdf-neko.git
4	mlton	 https://github.com/asdf-community/asdf-mlton.git
4	meson	 https [...]

2023-02-22 19:28 UTC, jdxcode requested changes

2023-02-22 19:28 UTC, jdxcode commented on .github/workflows/test-install-plugins.yml
> +    branches: [ "main" ]
let's just run this once per week, git tag, or with `workflow_dispatch`, otherwise it's a lot of noise for simple doc changes and things

2023-02-22 19:30 UTC, jdx commented on .github/workflows/test-install-plugins.yml
> +      - run: rtx install ${{matrix.plugin}}@latest
as mentioned, use `./e2e/test_top_runtimes`, though that test will need to be fixed to not just exit. We may need to put that behind an env var to gate it to only run from here, or put the script into `./scripts` or something. (I'm open)

2023-02-22 19:32 UTC, jdxcode commented
also, in case we need to generate that again here is the script I used: (maybe this should also go into ./scripts). It's fish though, bash would be better for compat:

```
for i in ~/.asdf/repository/plugins/*
          cat $i | \
                string split -f2 '=' | \
                string trim | \
                xargs -I '{}' gh repo view '{}' --json stargazerCount,name,owner | \
                jq -r "[.stargazerCount,\"$(basename $i)\",\"$(string split '=' -f2 (cat $i))\"]|@tsv" >> stargazer_count.txt
    end
cat stargazer_count.txt | sort -nr | uniq
```

2023-02-22 19:34 UTC, jdxcode commented
also: I'm fine with just installing for most of these runtimes as a starting point, I just think we should use those validations I have in test_top_runtimes since I already have them. For the rest of the top 50 or whatever we want we could just attempt to install.

Actually better yet: asdf has a `asdf plugin test` command which is what we probably should be using. I haven't replicated that in rtx yet though.

2023-02-22 20:29 UTC, jdxcode requested changes

2023-02-22 20:29 UTC, jdx commented on .github/workflows/test-install-plugins.yml
> +      - name: Rust Cache
don't bother with this, I am already thrashing the cache and this will make it worse. We can recompile from scratch every time

2023-02-22 20:31 UTC, jdxcode commented on .github/workflows/test-install-plugins.yml
> +            command: rtx exec elixir@latest erlang -- elixir --version
this one isn't working because erlang requires elixir, I think if you swap the order of these it might fix it
```suggestion
            command: rtx exec erlang elixir@latest -- elixir --version
```

2023-02-22 20:33 UTC, jdxcode commented on .github/workflows/test-install-plugins.yml
> +            command: rtx exec php@latest -- php -v php
try installing re2c with apt-get to see if it fixes this

2023-02-22 21:24 UTC, jdxcode commented on .github/workflows/test-install-plugins.yml
> +    name: Self Test popular plugins
```suggestion
```

delete this line, defaulting to `test-install-and-run` is better

2023-02-22 21:37 UTC, jdxcode commented on .github/workflows/test-install-plugins.yml
> -    tags: [ "v*" ]
keep this line in actually, we should test this on every release

2023-02-24 18:51 UTC, gerbal commented on .github/workflows/test-install-plugins.yml
> +      - run: rtx install ${{matrix.plugin}}@latest
I suggest leveraging Github Actions CI for mass testing of asdf plugins. It's a lot more efficient  to run all of these test installations in 70 parallel CI tasks than to run it all in serial in a single script.

Do you have any suggestions for how to expose failures from `e2e/test_top_runtimes` to quickly identify regressions  in a single plugin? Or to run the installations or tests in parallel?

2023-02-24 18:52 UTC, gerbal commented
FYI I have my own fork where the CI doesn't need approval to run - https://github.com/gerbal/rtx/pull/1

2023-02-24 19:44 UTC, jdxcode commented on .github/workflows/test-install-plugins.yml
> +      - run: scripts/build-tarball.sh x86_64-unknown-linux-gnu
the syntax for this changed, so you'll want to do this:

```suggestion
      - run: scripts/build-tarball.sh rtx --release --target x86_64-unknown-linux-gnu
```

2023-02-27 01:33 UTC, merged

2023-02-27 01:33 UTC, jdxcode commented
thanks for the help with this!